name: walking_rpg_mobile
description: Flutter client for the Walking RPG project.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_timezone: 5.1.0
  health: 13.3.1
  permission_handler: 12.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  config:
    enable-swift-package-manager: false
