import hashlib
import importlib.util
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


SCRIPT = Path(__file__).with_name("verify_flutter_pub_lock.py")
SPEC = importlib.util.spec_from_file_location("verify_flutter_pub_lock", SCRIPT)
assert SPEC is not None and SPEC.loader is not None
MODULE = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = MODULE
SPEC.loader.exec_module(MODULE)


class VerifyFlutterPubLockTest(unittest.TestCase):

    full_sha = "1" * 40

    @staticmethod
    def lock_source() -> str:
        return (
            "# Generated by pub\n"
            "packages:\n"
            "  flutter:\n"
            "    dependency: direct main\n"
            "    description: flutter\n"
            "    source: sdk\n"
            '    version: "0.0.0"\n'
            "  http:\n"
            "    dependency: direct main\n"
            "    description:\n"
            "      name: http\n"
            f"      sha256: {'a1' * 32}\n"
            '      url: "https://pub.dev"\n'
            "    source: hosted\n"
            '    version: "1.6.0"\n'
            "sdks:\n"
            '  dart: ">=3.10.3 <4.0.0"\n'
            '  flutter: ">=3.38.4"\n'
        )

    def validate_lock(self, source: str) -> list[str]:
        with tempfile.TemporaryDirectory() as directory:
            lock = Path(directory) / "pubspec.lock"
            lock.write_text(source, encoding="utf-8")
            return MODULE.validate_lockfile(
                lock,
                approved_sha256=hashlib.sha256(source.encode()).hexdigest(),
            )

    @classmethod
    def job(cls, consumer: str, *, runner: str = "ubuntu-24.04") -> str:
        return (
            f"    runs-on: {runner}\n"
            "    defaults:\n"
            "      run:\n"
            "        working-directory: mobile\n"
            "    steps:\n"
            f"      - uses: actions/checkout@{cls.full_sha}\n"
            f"      - uses: subosito/flutter-action@{cls.full_sha}\n"
            "      - name: Install dependencies\n"
            "        run: flutter pub get --enforce-lockfile\n"
            "      - name: Consume dependencies\n"
            f"        run: {consumer}\n"
        )

    def valid_workflows(self) -> dict[str, str]:
        return {
            "ci.yml": (
                "jobs:\n"
                "  mobile:\n"
                + self.job("flutter analyze --no-pub")
                + "  android-host:\n"
                + self.job("flutter build apk --debug --no-pub")
                + "  ios-host:\n"
                + self.job(
                    "flutter build ios --simulator --debug --no-pub",
                    runner="macos-26",
                )
            ),
            "release-quality.yml": (
                "jobs:\n"
                "  android-release:\n"
                + self.job("flutter build appbundle --release --no-pub")
                + "  ios-release:\n"
                + self.job(
                    "flutter build ios --release --no-codesign --no-pub",
                    runner="macos-26",
                )
            ),
        }

    @staticmethod
    def validate_workflows(files: dict[str, str]) -> list[str]:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            for name, source in files.items():
                (root / name).write_text(source, encoding="utf-8")
            return MODULE.validate_workflows(root)

    def test_accepts_reviewed_lock_and_frozen_workflows(self):
        self.assertEqual([], self.validate_lock(self.lock_source()))
        self.assertEqual([], self.validate_workflows(self.valid_workflows()))

    def test_rejects_changed_lock_bytes(self):
        source = self.lock_source()
        with tempfile.TemporaryDirectory() as directory:
            lock = Path(directory) / "pubspec.lock"
            lock.write_text(source + "# changed\n", encoding="utf-8")
            errors = MODULE.validate_lockfile(
                lock,
                approved_sha256=hashlib.sha256(source.encode()).hexdigest(),
            )
        self.assertTrue(any("reviewed SHA-256" in error for error in errors))

    def test_rejects_ranges_bad_hashes_and_unreviewed_sources(self):
        source = self.lock_source()
        cases = (
            source.replace('version: "1.6.0"', 'version: ">=1.0.0"'),
            source.replace("a1" * 32, "A1" * 32),
            source.replace("https://pub.dev", "https://mirror.invalid"),
            source.replace("source: hosted", "source: git"),
            source.replace("name: http", "name: other"),
        )
        for candidate in cases:
            with self.subTest(candidate=candidate):
                self.assertTrue(self.validate_lock(candidate))

    def test_rejects_missing_extra_and_invalid_package_fields(self):
        source = self.lock_source()
        cases = (
            source.replace("    dependency: direct main\n", "", 1),
            source.replace(
                "    source: hosted\n",
                "    source: hosted\n    checksum: bypass\n",
            ),
            source.replace("  http:\n", "  HTTP:\n"),
            source.replace("description: flutter", "description: dart"),
            source.replace("dependency: direct main", "dependency: optional", 1),
            source.replace("sdks:\n", "other: value\nsdks:\n"),
        )
        for candidate in cases:
            with self.subTest(candidate=candidate):
                self.assertTrue(self.validate_lock(candidate))

    def test_rejects_lock_yaml_duplicates_aliases_merges_and_documents(self):
        source = self.lock_source()
        cases = (
            source.replace("sdks:\n", "  http: {}\nsdks:\n"),
            "value: &value locked\ncopy: *value\n" + source,
            "defaults: &defaults\n  source: hosted\n"
            + source.replace("    source: hosted\n", "    <<: *defaults\n"),
            source + "---\npackages: {}\n",
            "packages: [unterminated\n",
        )
        for candidate in cases:
            with self.subTest(candidate=candidate):
                self.assertTrue(self.validate_lock(candidate))

    def test_requires_exact_enforced_get_in_every_protected_job(self):
        replacements = (
            "flutter pub get",
            "flutter pub upgrade --major-versions",
            "dart pub get --enforce-lockfile",
            "flutter pub get --no-enforce-lockfile",
            "flutter pub get --enforce-lockfile || true",
        )
        for replacement in replacements:
            files = self.valid_workflows()
            files["ci.yml"] = files["ci.yml"].replace(
                "flutter pub get --enforce-lockfile",
                replacement,
                1,
            )
            with self.subTest(replacement=replacement):
                self.assertTrue(self.validate_workflows(files))

    def test_rejects_wrapped_path_qualified_and_nested_extra_resolvers(self):
        commands = (
            "sudo flutter pub get",
            "/opt/flutter/bin/flutter pub upgrade",
            "env MODE=ci dart pub get",
            "bundle exec flutter pub get",
            "sh -c 'flutter pub upgrade'",
            "bash -lc 'flutter pub upgrade'",
            "fvm flutter pub get --enforce-lockfile",
        )
        for command in commands:
            files = self.valid_workflows()
            files["ci.yml"] += (
                "  unprotected:\n"
                "    steps:\n"
                "      - run: |\n"
                f"          {command}\n"
            )
            with self.subTest(command=command):
                self.assertTrue(self.validate_workflows(files))

    def test_allows_comments_and_non_executable_textual_mentions(self):
        files = self.valid_workflows()
        files["ci.yml"] += (
            "  documentation:\n"
            "    steps:\n"
            "      - run: |\n"
            "          echo 'do not run flutter pub get'\n"
            "          printf '%s\\n' 'dart pub upgrade'\n"
            "          # sudo /opt/flutter/bin/flutter pub get\n"
        )
        self.assertEqual([], self.validate_workflows(files))

    def test_rejects_missing_reordered_conditional_and_extra_install_steps(self):
        install = (
            "      - name: Install dependencies\n"
            "        run: flutter pub get --enforce-lockfile\n"
        )
        consumer = (
            "      - name: Consume dependencies\n"
            "        run: flutter analyze --no-pub\n"
        )
        cases: list[dict[str, str]] = []

        missing = self.valid_workflows()
        missing["ci.yml"] = missing["ci.yml"].replace(install, "", 1)
        cases.append(missing)

        reordered = self.valid_workflows()
        reordered["ci.yml"] = reordered["ci.yml"].replace(
            install + consumer,
            consumer + install,
            1,
        )
        cases.append(reordered)

        conditional = self.valid_workflows()
        conditional["ci.yml"] = conditional["ci.yml"].replace(
            "      - name: Install dependencies\n",
            "      - name: Install dependencies\n        if: ${{ false }}\n",
            1,
        )
        cases.append(conditional)

        tolerated = self.valid_workflows()
        tolerated["ci.yml"] = tolerated["ci.yml"].replace(
            "      - name: Install dependencies\n",
            "      - name: Install dependencies\n        continue-on-error: true\n",
            1,
        )
        cases.append(tolerated)

        job_bypass = self.valid_workflows()
        job_bypass["ci.yml"] = job_bypass["ci.yml"].replace(
            "    runs-on: ubuntu-24.04\n",
            "    runs-on: ubuntu-24.04\n    if: ${{ false }}\n",
            1,
        )
        cases.append(job_bypass)

        extra = self.valid_workflows()
        extra["ci.yml"] += (
            "  extra:\n"
            "    steps:\n"
            "      - run: flutter pub get --enforce-lockfile\n"
        )
        cases.append(extra)

        for files in cases:
            with self.subTest(files=files):
                self.assertTrue(self.validate_workflows(files))

    def test_rejects_wrong_working_directory_and_missing_setup_or_consumer(self):
        replacements = (
            ("working-directory: mobile", "working-directory: ."),
            ("subosito/flutter-action", "example/setup-flutter"),
            ("flutter analyze --no-pub", "echo skipped"),
            ("flutter analyze --no-pub", "flutter analyze"),
            ("flutter analyze --no-pub", "flutter analyze --no-pub --pub"),
        )
        for old, new in replacements:
            files = self.valid_workflows()
            files["ci.yml"] = files["ci.yml"].replace(old, new, 1)
            with self.subTest(replacement=new):
                self.assertTrue(self.validate_workflows(files))

    def test_rejects_invalid_workflow_yaml_ambiguity_and_hidden_yaml_resolver(self):
        cases = (
            {"ci.yml": "jobs: [unterminated\n", "release-quality.yml": "jobs: {}\n"},
            {
                **self.valid_workflows(),
                "hidden.yaml": "jobs:\n  hidden:\n    steps:\n      - run: dart pub upgrade\n",
            },
            {
                "ci.yml": "job: &job\n" + self.job("flutter analyze --no-pub")
                + "jobs:\n  mobile: *job\n",
                "release-quality.yml": "jobs: {}\n",
            },
            {
                "ci.yml": "jobs:\n  mobile: {}\n  mobile: {}\n",
                "release-quality.yml": "jobs: {}\n",
            },
            {
                "ci.yml": "jobs: {}\n---\njobs: {}\n",
                "release-quality.yml": "jobs: {}\n",
            },
        )
        for files in cases:
            with self.subTest(files=files):
                self.assertTrue(self.validate_workflows(files))

    def test_tracking_requires_lock_and_rejects_overrides_or_generated_paths(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            subprocess.run(["git", "init", "-q", str(root)], check=True)
            lock = root / "mobile/pubspec.lock"
            lock.parent.mkdir(parents=True)
            lock.write_text(self.lock_source(), encoding="utf-8")
            missing = MODULE.validate_tracking(root)
            self.assertTrue(any("tracked" in error for error in missing))

            subprocess.run(["git", "-C", str(root), "add", str(lock)], check=True)
            self.assertEqual([], MODULE.validate_tracking(root))

            (root / ".gitignore").write_text(
                "mobile/pubspec.lock\n", encoding="utf-8"
            )
            ignored = MODULE.validate_tracking(root)
            self.assertTrue(any("must not be ignored" in error for error in ignored))

            override = root / "mobile/pubspec_overrides.yaml"
            override.write_text("dependency_overrides: {}\n", encoding="utf-8")
            overridden = MODULE.validate_tracking(root)
            self.assertTrue(any("must not exist" in error for error in overridden))

            generated = root / "mobile/.dart_tool/package_config.json"
            generated.parent.mkdir(parents=True)
            generated.write_text("{}\n", encoding="utf-8")
            subprocess.run(
                ["git", "-C", str(root), "add", "-f", str(generated)],
                check=True,
            )
            generated_errors = MODULE.validate_tracking(root)
            self.assertTrue(
                any("generated or overriding" in error for error in generated_errors)
            )

    def test_fails_closed_without_inputs_or_reviewed_parser(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            self.assertTrue(MODULE.validate_lockfile(root / "pubspec.lock"))
            self.assertTrue(MODULE.validate_workflows(root))

        original = MODULE.yaml.__version__
        MODULE.yaml.__version__ = "0.0.0"
        try:
            self.assertTrue(self.validate_lock(self.lock_source()))
            self.assertTrue(self.validate_workflows(self.valid_workflows()))
        finally:
            MODULE.yaml.__version__ = original

    def test_repository_matches_reviewed_contract(self):
        self.assertEqual([], MODULE.validate_repository())


if __name__ == "__main__":
    unittest.main()
