import 'package:walking_rpg_mobile/core/cache/read_snapshot_cache.dart';
import 'package:walking_rpg_mobile/features/platform/domain/platform_command_result.dart';
import 'package:walking_rpg_mobile/features/platform/domain/platform_snapshot.dart';

Map<String, dynamic> platformSnapshotJson({
  int stateVersion = 3,
  List<String> completedOnboardingSteps = const <String>['welcome'],
  String activePetId = 'spark-v1',
  String sparkName = 'Искра',
  int sparkLevel = 1,
  int sparkBond = 50,
  int sparkEvolutionStage = 0,
  int sparkEvolutionBond = 50,
  int? sparkMaximumEvolutionStage,
  int seasonXp = 220,
  int? seasonXpPerLevel = 100,
  int weeklyRouteProgress = 40,
  int weeklyRouteRequiredEnergy = 100,
  Map<String, dynamic>? squad,
  List<String> ownedCosmetics = const <String>['pilot-scarf'],
  String? activeCosmeticId = 'pilot-scarf',
  Map<String, String> equippedCosmetics = const <String, String>{
    'PILOT': 'pilot-scarf',
  },
  List<String> achievements = const <String>['season-reward-1'],
  int resolvedEventCount = 2,
  int totalAcceptedSteps = 6842,
  bool? hasSuccessfulActivitySync,
  bool sandboxPaymentsEnabled = true,
  bool includeProfileCosmetics = false,
  CachedReadMetadata? cacheMetadata,
}) {
  const List<String> onboardingSteps = <String>[
    'welcome',
    'health-permission',
    'first-sync',
    'pet-selection',
    'first-expedition',
    'first-event',
  ];
  final bool onboardingComplete = completedOnboardingSteps.toSet().containsAll(
    onboardingSteps,
  );
  return <String, dynamic>{
    'contentVersion': 'chapter-1-v1',
    'stateVersion': stateVersion,
    'userState': <String, dynamic>{
      'activePetId': activePetId,
      'pets': <Map<String, dynamic>>[
        <String, dynamic>{
          'petId': 'spark-v1',
          'name': sparkName,
          'species': 'люмин',
          'trait': 'Чуткий разведчик',
          'level': sparkLevel,
          'bond': sparkBond,
          'evolutionStage': sparkEvolutionStage,
          'evolutionBond': sparkEvolutionBond,
          if (sparkMaximumEvolutionStage != null)
            'maximumEvolutionStage': sparkMaximumEvolutionStage,
          'active': activePetId == 'spark-v1',
        },
        <String, dynamic>{
          'petId': 'moss-v1',
          'name': 'Мох',
          'species': 'терра',
          'trait': 'Спокойный хранитель',
          'level': 1,
          'bond': 12,
          'evolutionStage': 0,
          'evolutionBond': 45,
          'active': activePetId == 'moss-v1',
        },
        <String, dynamic>{
          'petId': 'rune-v1',
          'name': 'Навигатор',
          'species': 'эхо',
          'trait': 'Точный проводник',
          'level': 1,
          'bond': 9,
          'evolutionStage': 0,
          'evolutionBond': 55,
          'active': activePetId == 'rune-v1',
        },
      ],
      'completedOnboardingSteps': completedOnboardingSteps,
      'onboardingComplete': onboardingComplete,
      'unlockedSkills': <String>['steady-step'],
      'quests': <Map<String, dynamic>>[
        <String, dynamic>{
          'questId': 'walk-3000',
          'name': 'Первый маршрут',
          'metric': 'TOTAL_ACCEPTED_STEPS',
          'progress': 3000,
          'target': 3000,
          'ready': true,
          'claimed': false,
          'seasonXpReward': 60,
          'petBondReward': 4,
        },
        <String, dynamic>{
          'questId': 'resolve-3',
          'name': 'Исследователь',
          'metric': 'RESOLVED_EVENTS',
          'progress': 2,
          'target': 3,
          'ready': false,
          'claimed': false,
          'seasonXpReward': 80,
          'petBondReward': 5,
        },
      ],
      'claimedQuests': <String>[],
      'achievements': achievements,
      'seasonXp': seasonXp,
      'seasonLevel': seasonXp ~/ 100 + 1,
      'weeklyRouteProgress': weeklyRouteProgress,
      'weeklyRouteRequiredEnergy': weeklyRouteRequiredEnergy,
      'squad': squad,
      'ownedCosmetics': ownedCosmetics,
      'activeCosmeticId': activeCosmeticId,
      'equippedCosmetics': equippedCosmetics,
      'experimentAssignments': <String, String>{
        'home-energy-copy-v1': 'MOTIVATIONAL',
        'quest-order-v1': 'REWARD_FIRST',
      },
      'resolvedEventCount': resolvedEventCount,
      'totalAcceptedSteps': totalAcceptedSteps,
      'hasSuccessfulActivitySync':
          hasSuccessfulActivitySync ?? totalAcceptedSteps > 0,
    },
    'content': <String, dynamic>{
      'contentVersion': 'chapter-1-v1',
      'chapterNodes': 18,
      'onboardingSteps': onboardingSteps,
      'pets': const <Map<String, dynamic>>[],
      'skills': <Map<String, dynamic>>[
        <String, dynamic>{
          'skillId': 'steady-step',
          'name': 'Ровный шаг',
          'description': 'Стабилизирует серии активности.',
          'requiredSeasonXp': 0,
        },
        <String, dynamic>{
          'skillId': 'trail-memory',
          'name': 'Память маршрута',
          'description': 'Открывает сведения о пройденных узлах.',
          'requiredSeasonXp': 100,
        },
      ],
      'quests': const <Map<String, dynamic>>[],
      'achievements': <Map<String, dynamic>>[
        <String, dynamic>{
          'achievementId': 'onboarding-complete',
          'name': 'Путь открыт',
        },
        <String, dynamic>{
          'achievementId': 'season-level-3',
          'name': 'Третий уровень сезона',
        },
      ],
      'cosmetics': <Map<String, dynamic>>[
        <String, dynamic>{
          'cosmeticId': 'pilot-scarf',
          'name': 'Шарф навигатора',
          'slot': 'PILOT',
          'sandboxPrice': 0,
        },
        <String, dynamic>{
          'cosmeticId': 'spark-halo',
          'name': 'Ореол Искры',
          'slot': 'PET',
          'sandboxPrice': 199,
        },
        if (includeProfileCosmetics) ...<Map<String, dynamic>>[
          <String, dynamic>{
            'cosmeticId': 'trail-banner',
            'name': 'Знамя маршрута',
            'slot': 'PROFILE',
            'sandboxPrice': 299,
          },
          <String, dynamic>{
            'cosmeticId': 'dawn-frame',
            'name': 'Рамка рассвета',
            'slot': 'PROFILE',
            'sandboxPrice': 399,
          },
        ],
      ],
      'experiments': <Map<String, dynamic>>[
        <String, dynamic>{
          'experimentId': 'home-energy-copy-v1',
          'variants': <String>['CONTROL', 'MOTIVATIONAL'],
          'description': 'Текст блока энергии',
        },
        <String, dynamic>{
          'experimentId': 'quest-order-v1',
          'variants': <String>['PROGRESS_FIRST', 'REWARD_FIRST'],
          'description': 'Порядок карточки задания',
        },
      ],
      'season': <String, dynamic>{
        'seasonId': 'signal-season-1',
        'name': 'Сезон первого сигнала',
        'levels': 10,
        if (seasonXpPerLevel != null) 'xpPerLevel': seasonXpPerLevel,
      },
      'weeklyRoute': <String, dynamic>{
        'routeId': 'weekly-route-1',
        'requiredEnergy': 120,
      },
      'materials': <String>['lumen-shard'],
      'catalogDigest': 'fixture-digest',
    },
    'remoteConfig': <String, dynamic>{
      'backgroundHealthSyncEnabled': false,
      'activityRetentionDays': 30,
      'seasonId': 'signal-season-1',
      'weeklyRouteEnergy': weeklyRouteRequiredEnergy,
      'sandboxPaymentsEnabled': sandboxPaymentsEnabled,
      'weeklyRouteEnabled': true,
    },
    'serverTime': '2026-07-27T10:00:00Z',
  };
}

PlatformSnapshot platformSnapshot({
  int stateVersion = 3,
  List<String> completedOnboardingSteps = const <String>['welcome'],
  String activePetId = 'spark-v1',
  String sparkName = 'Искра',
  int sparkLevel = 1,
  int sparkBond = 50,
  int sparkEvolutionStage = 0,
  int sparkEvolutionBond = 50,
  int? sparkMaximumEvolutionStage,
  int seasonXp = 220,
  int? seasonXpPerLevel = 100,
  int weeklyRouteProgress = 40,
  Map<String, dynamic>? squad,
  List<String> ownedCosmetics = const <String>['pilot-scarf'],
  String? activeCosmeticId = 'pilot-scarf',
  Map<String, String> equippedCosmetics = const <String, String>{
    'PILOT': 'pilot-scarf',
  },
  List<String> achievements = const <String>['season-reward-1'],
  int resolvedEventCount = 2,
  int totalAcceptedSteps = 6842,
  bool? hasSuccessfulActivitySync,
  bool sandboxPaymentsEnabled = true,
  bool includeProfileCosmetics = false,
  CachedReadMetadata? cacheMetadata,
}) {
  return PlatformSnapshot.fromJson(
    platformSnapshotJson(
      stateVersion: stateVersion,
      completedOnboardingSteps: completedOnboardingSteps,
      activePetId: activePetId,
      sparkName: sparkName,
      sparkLevel: sparkLevel,
      sparkBond: sparkBond,
      sparkEvolutionStage: sparkEvolutionStage,
      sparkEvolutionBond: sparkEvolutionBond,
      sparkMaximumEvolutionStage: sparkMaximumEvolutionStage,
      seasonXp: seasonXp,
      seasonXpPerLevel: seasonXpPerLevel,
      weeklyRouteProgress: weeklyRouteProgress,
      squad: squad,
      ownedCosmetics: ownedCosmetics,
      activeCosmeticId: activeCosmeticId,
      equippedCosmetics: equippedCosmetics,
      achievements: achievements,
      resolvedEventCount: resolvedEventCount,
      totalAcceptedSteps: totalAcceptedSteps,
      hasSuccessfulActivitySync: hasSuccessfulActivitySync,
      sandboxPaymentsEnabled: sandboxPaymentsEnabled,
      includeProfileCosmetics: includeProfileCosmetics,
    ),
    cacheMetadata: cacheMetadata,
  );
}

PlatformCommandResult platformCommandResult({
  required String commandType,
  required String idempotencyKey,
  required PlatformSnapshot snapshot,
  String message = 'Команда выполнена',
}) {
  return PlatformCommandResult(
    commandType: commandType,
    idempotencyKey: idempotencyKey,
    message: message,
    stateVersion: snapshot.stateVersion,
    snapshot: snapshot,
    serverTime: snapshot.serverTime,
  );
}
